spring:
  ai:
    openai:
      api-key: sk-ae18f05c2da84119b31db577e7f68538
    ollama:
      base-url: http://140.143.170.96:11434
      chat:
        model: qwen2.5:1.5b
      embedding:
        model: qwen2.5:1.5b
server:
  port: 8081

logging:
  level:
    org: debug
